'use client';

import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
  formatDate: (date: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  zh: {
    'home.title': 'Flipflop Pathfinders',
    'home.hero.title': '👣 欢迎来到Flipflop Pathfinders寻路者计划',
    'home.subtitle': '这是为热爱Flipflop 和 Web3创新的伙伴们量身打造的社区，致力于推动公平、公正、社区驱动的Launchpad生态。',
    'home.join': '立即加入',
    'home.learn': '了解流程',
    'home.description': '我们采用 Proof of Mint (PoM) 与 URC 推荐机制，鼓励建设者、创作者与传播者为新项目注入活力，并在内容、活动与合作中留下属于自己的脚印。在这里，你能找到志同道合的伙伴，共同见证项目从 铸造（Mint）到毕业进入外部市场 的成长过程。Flipflop 不只是一个发币平台，而是一个开放的创造舞台，让更多想法得以落地，实现从零到一的成长!',
    'home.features.builder.title': '建设者激励',
    'home.features.builder.desc': '为项目注入活力',
    'home.features.community.title': '社区协作',
    'home.features.community.desc': '志同道合的伙伴',
    'home.features.growth.title': '从零到一',
    'home.features.growth.desc': '创意落地实现',
    'home.mission.title': '🎯 Flipflop 寻路者计划的目标',
    'home.mission.community': '通过内容创作与活动，壮大 Flipflop 的全球社区影响力',
    'home.mission.incubation': '陪伴新项目完成孵化，推动 Web3 创业者从零到一',
    'home.mission.rewards': '为优秀贡献者提供奖励、周边与创业支持',
    'home.mission.builder': '打造一个自由、开放、互相成就的建设者社区',
    'home.mission.footprints': '让每一位参与者都能在 Flipflop 的生态中留下脚印',
    'home.mission.quote': '"加入社区，留下属于你的脚印，成为塑造 Web3 创业未来的共建者"',
    'home.features.honor.title': '荣誉体系',
    'home.features.honor.desc': 'Flipprints 👣荣誉体系，每一份贡献都会化为"脚印"留在 Flipflop 的生态里',
    'home.features.ranking.desc': '实时更新的Flipprints排行榜，激励你不断前行',
    'home.features.forms.desc': '多种申请表格，支持在线提交和审核',
    'home.social.title': '关注我们！',
    'home.social.desc': 'flipflop会发布最新活动和相关生态进展。',
    'home.social.global': '全球交流群',
    'home.social.chinese': '中文交流群',
    'honor.title': '荣誉体系',
    'honor.subtitle': '通过贡献积累「Flipprints」（👣脚印），晋升以下不同等级，获得专属荣誉与特权。',
    'ranking.title': 'Flipprints排行榜',
    'ranking.subtitle': '实时更新的用户Flipprints排名',
    'process.title': '参与流程',
    'process.subtitle': '了解如何参与Pathfinders Program项目',
    'forms.title': '表格申请',
    'forms.subtitle': '选择你需要提交的表格类型',
    'login.title': '登录',
    'register.title': '注册',
    'profile.title': '个人中心',
    'admin.title': '管理员后台',
    'theme.toggle': '切换主题',
    'language.toggle': '切换语言',
    'user.welcome': '欢迎',
    'user.logout': '退出',
    'honor.page.title': '✨ 成为Pathfinders，你将获得什么？',
    'honor.page.subtitle': '通过贡献积累「Flipprints」（👣脚印），晋升不同等级，获得专属荣誉与特权',
    'honor.level.l1': 'L1 Explorer（探索者）',
    'honor.level.l2': 'L2 Pathfinder（探路者）',
    'honor.level.l3': 'L3 Trailblazer（开路者）',
    'honor.level.l4': 'L4 Pioneer（先驱者）',
    'honor.benefits': '权益:',
    'honor.monthly.title': '💡 月度激励',
    'honor.monthly.subtitle': '每一位 Pathfinders成员，只要完成当月基础任务清单，即可获得 10U 基础奖励。',
    'honor.table.completion': '完成情况',
    'honor.table.reward': '奖励金额',
    'honor.table.requirements': '具体任务要求',
    'honor.flipprints.title': '🔗 Flipprints贡献参考',
    'honor.table.category': '类别',
    'honor.table.task': '任务类型',
    'honor.table.points': 'Flipprints范围',
    'honor.table.notes': '备注',
    'honor.notice.title': '重要说明',
    'honor.notice.1': '每月Flipprints上限：50分，超过上限不计入Flipprints排行榜',
    'honor.notice.2': '分数将于每周周日统一整理，更新于排行榜',
    'honor.notice.3': '每月奖金将于月底结算后，次月第一周统一发放',
    'honor.notice.4': '等级累计不会清零，每一步脚印，都是你与 Flipflop 共同成长的印记',
    // Honor level benefits
    'honor.l1.benefit.1': '获得 Explorer 社群身份标识（社群头衔）',
    'honor.l1.benefit.2': '加入 Pathfinders 专属频道（Telegram）',
    'honor.l1.benefit.3': '优先获取平台官方资讯与任务通知',
    'honor.l1.benefit.4': '获得不定期福利，空投参与资格',
    'honor.l2.benefit.1': '获得 Pathfinder 身份标识（社群头衔）',
    'honor.l2.benefit.2': '获得 Flipflop 定制周边（T恤/贴纸包）抽奖资格',
    'honor.l2.benefit.3': '参与月度线上闭门分享会（学习生态趋势/案例解读）',
    'honor.l2.benefit.4': '有机会加入小规模线下工作坊或游学营',
    'honor.l3.benefit.1': '优先成为 AMA/线上活动的嘉宾或联合主持',
    'honor.l3.benefit.2': '授予Flipflop社区Trailblazer头衔，可用于X主页展示',
    'honor.l3.benefit.3': '获得 Flipflop 生态项目提前测试资格（内测白名单）',
    'honor.l3.benefit.4': '获得资源库访问权（投研资料、演讲 PPT、学习手册）',
    'honor.l3.benefit.5': '每季度一次与核心团队闭门讨论会',
    'honor.l4.benefit.1': '获得限量周边礼包及荣誉NFT',
    'honor.l4.benefit.2': '登上 Flipflop 荣誉榜单，永久展示',
    'honor.l4.benefit.3': '直接参与平台战略讨论（路线建议、产品内测优先权）',
    'honor.l4.benefit.4': '获得创业支持通道（介绍给孵化器/基金，提供初步对接）',
    'honor.l4.benefit.5': '获得长期合作机会（作为社区合伙人/活动联合主理人）',
    // Monthly incentive table
    'honor.monthly.basic.completion': '基础任务完成',
    'honor.monthly.basic.reward': '10U/月',
    'honor.monthly.basic.requirements': '传播类：每周≥1次"一键三联"（转发+点赞+评论），当月≥4次\n创作类：每月至少2条原创内容（Meme/推文/教程任选）\n社区类：参与≥1次社群互动（在AMA上作为speaker提问/分享，或Telegram参与话题讨论）',
    'honor.monthly.advanced1.completion': '进阶 I',
    'honor.monthly.advanced1.reward': '50U/月',
    'honor.monthly.advanced1.requirements': '传播类：≥8次"一键三联"\n创作类：≥4条原创内容（可含短视频/图文教程）\n社区类：≥2次社群互动',
    'honor.monthly.advanced2.completion': '进阶 II',
    'honor.monthly.advanced2.reward': '100U/月',
    'honor.monthly.advanced2.requirements': '传播类：≥10次"一键三联"\n创作类：≥8条原创内容（至少1篇500字以上长篇文章或1个原创短视频）\n社区类：≥3次社群互动',
    'honor.monthly.advanced3.completion': '进阶 III',
    'honor.monthly.advanced3.reward': '200U/月',
    'honor.monthly.advanced3.requirements': '传播类：≥12次"一键三联"\n创作类：≥12条原创内容（至少2篇500字以上长篇文章或2个原创视频）\n社区类：≥4次社群互动（至少1篇500字以上AMA Recap）',
    'honor.monthly.special.completion': '特别奖励',
    'honor.monthly.special.reward': '500U/月',
    'honor.monthly.special.requirements': '满足进阶III全部内容后\n需满足额外贡献，≥1项包括：\n1. 出现爆款内容（高传播文章/视频/Meme）\n2. 成功组织大型活动（AMA、Space、Meetup）\n3. 为Flipflop引入关键合作资源',
    'honor.monthly.special.note': '如需组织活动，可以在此提前申请，包含相关经费与需求',
    'honor.monthly.special.link': '活动申请表',
    'honor.monthly.definitions.title': '参与月度激励奖金活动需注意以下细节：',
    'honor.monthly.definitions.promotion': '传播类一键3联：在X上转发，点赞，评论同1条官方公告/活动内容',
    'honor.monthly.definitions.creation': '创作类内容：任何原创内容，在X上发布时需 @官方账号 及#FFPP',
    'honor.monthly.definitions.official.link': 'https://x.com/flipfloplaunch',
    'honor.monthly.definitions.community': '社区类社群互动：包含参与社区线上活动或AMA上作为speaker提问/分享，或Telegram参与话题讨论，有效发言，并截图保留参与痕迹',
    'honor.flipprints.submit.note': '任务完成后，请务必截图留存，并通过',
    'honor.flipprints.submit.link': '成果提交表',
    'honor.flipprints.submit.text': '统一提交',
    'honor.notice.5': '基础奖金与进阶奖金不重复发放',
    'honor.warning.title': '重要警告',
    'honor.warning.text': '注：若出现抄袭，恶意刷分等现象，将被删除全部分数，当月奖金不会发放，并永久取消参与Flipflop活动资格',
    // Flipprints contribution table
    'honor.flipprints.promotion.category': '传播类',
    'honor.flipprints.promotion.task': 'X 官方内容一键三联',
    'honor.flipprints.promotion.points': '+0.5',
    'honor.flipprints.promotion.notes': '单纯转发/点赞不计分',
    'honor.flipprints.creation.category': '创作类',
    'honor.flipprints.creation.task1': '原创内容/ Meme / 平台图文教程',
    'honor.flipprints.creation.points1': '+2',
    'honor.flipprints.creation.notes1': '月Flipprints上限：10分',
    'honor.flipprints.creation.task2': '长篇或深度文章 (不少于500字)',
    'honor.flipprints.creation.points2': '+8-10',
    'honor.flipprints.creation.notes2': '强调原创',
    'honor.flipprints.creation.task3': '短视频（不少于30秒）',
    'honor.flipprints.creation.points3': '+12-15',
    'honor.flipprints.creation.notes3': '强调原创，半原创Flipprints减半',
    'honor.flipprints.community.category': '社区类',
    'honor.flipprints.community.task1': '参加AMA / 线上活动，提问或参与讨论',
    'honor.flipprints.community.points1': '+2-3',
    'honor.flipprints.community.notes1': '需作为Speaker发言',
    'honor.flipprints.community.task2': 'AMA Recap（不少于500字）',
    'honor.flipprints.community.points2': '+8-10',
    'honor.flipprints.community.notes2': 'Twitter发布并@官方账号',
    'honor.flipprints.community.task3': '成功组织一场官方认证线下活动',
    'honor.flipprints.community.points3': '+25-30',
    'honor.flipprints.community.notes3': '高投入任务，单次高分',
    'honor.flipprints.viral.category': '高传播内容',
    'honor.flipprints.viral.task': '任何原创内容获得广泛关注',
    'honor.flipprints.viral.points': '×1.5–3倍',
    'honor.flipprints.viral.notes': '针对爆款内容的额外奖励',
    // Ranking page
    'ranking.page.title': 'Flipprints排行榜',
    'ranking.page.subtitle': '实时更新的用户Flipprints排名',
    'ranking.top10.title': 'Top 10 用户',
    'ranking.table.rank': '排名',
    'ranking.table.username': '用户名',
    'ranking.table.points': 'Flipprints',
    'ranking.table.level': '等级',
    'ranking.points.unit': '分',
    'ranking.myrank.title': '我的排名',
    'ranking.myrank.rank': '排名',
    'ranking.myrank.points': 'Flipprints',
    'ranking.myrank.level': '等级',
    'ranking.myrank.completion': '完成度',
    'ranking.currentuser': '当前用户',
    'ranking.improve.link': '提升排名，立即提交表单 →',
    'ranking.level.diamond': '钻石',
    'ranking.level.platinum': '铂金',
    'ranking.level.gold': '黄金',
    'ranking.level.silver': '白银',
    'ranking.level.bronze': '青铜',
    'ranking.table.twitter': '推特',
    'ranking.total.points': '总Flipprints',
    'ranking.reference.note': '详细Flipprints计算可参考',
    'ranking.reference.link': '荣誉体系',
    // Process page
    'process.page.title': '🌟 如何参与 Flipflop Pathfinders 计划？',
    'process.page.subtitle': '了解如何参与Pathfinders Program项目',
    'process.step1.title': '申请加入',
    'process.step1.description': '填写「官网申请表」，留下你的基本信息（昵称、社交账号、钱包地址）',
    'process.step1.detail1': '告诉我们你的擅长方向（内容创作 / 社群活动 / 研究写作 / 推广传播）',
    'process.step1.detail2': '展示一些代表性的作品',
    'process.step1.detail3': '一段简短的自我介绍，让我们知道你为什么想加入 Pathfinders',
    'process.step1.detail4': '通过审核后，你将被邀请进入专属社群',
    'process.step2.title': '完成任务，积累脚印',
    'process.step2.description': '基础任务（解锁月度奖励资格）和进阶任务（冲击高额奖励）',
    'process.step2.detail1': '基础任务：每周点赞/转发/评论官方内容',
    'process.step2.detail2': '创作表达：每月发布 2 条原创内容（Meme、短推文或图文教程）',
    'process.step2.detail3': '社区共建：每月至少参与 1 次 AMA/Telegram话题讨论',
    'process.step2.detail4': '进阶任务：撰写深度文章、制作视频、举办活动',
    'process.step3.title': '提交成果',
    'process.step3.description': '所有任务成果需通过「提交表单」上传',
    'process.step3.detail1': '包括：任务类型、内容链接、截图证明、钱包地址',
    'process.step3.detail2': '日常内容可随时提交，推荐每周一次',
    'process.step3.detail3': '月底前需完成当月总结提交',
    'process.step3.detail4': '所有提交内容将被审核评分',
    'process.step4.title': '审核与Flipprints榜',
    'process.step4.description': 'Pathfinders Program运营团队会从四个维度进行审核与评分',
    'process.step4.detail1': '内容质量：原创性、深度、价值',
    'process.step4.detail2': '传播影响力：阅读量、互动量、传播范围',
    'process.step4.detail3': '社区价值：对社区建设的贡献度',
    'process.step4.detail4': '完成度：任务完成的质量和及时性',
    'process.step5.title': '获得奖励',
    'process.step5.description': '完成基础任务即可获得 10U 基础奖励；优秀贡献者可获得 50U – 500U 的高阶奖励',
    'process.step5.detail1': '所有奖励将通过链上（Solana 地址 / USDT）安全发放',
    'process.step5.detail2': '每周Flipprints榜单公开更新，透明、公正',
    'process.step5.detail3': '你的脚印不仅代表奖励，更是你在 Flipflop 社区的成长轨迹',
    'process.step5.detail4': '等级提升后享受对应权益和特权',
    'process.step6.title': '持续成长',
    'process.step6.description': '和全球伙伴一起留下属于你的脚印，塑造 Web3 的未来',
    'process.step6.detail1': '积累 Flipprints 👣 提升等级',
    'process.step6.detail2': '解锁更多权益和合作机会',
    'process.step6.detail3': '成为 Flipflop 生态的核心建设者',
    'process.step6.detail4': '享受创业支持和融资对接机会',
    'process.details.title': '具体内容:',
    'process.register.link': '立即注册 →',
    'process.forms.link': '开始填写申请表 →',
    'process.application.form': '官网申请表',
    'process.achievement.form': '提交成果的提交表单',
    'process.activity.form': '活动申请表',
    'process.notice.title': '重要提示',
    'process.notice.1': '任务完成后，请务必截图留存，并通过成果提交表统一提交',
    'process.notice.2': '每月Flipprints上限：50分，超过上限不计入Flipprints排行榜',
    'process.notice.3': '分数将于每周周日统一整理，更新于排行榜',
    'process.notice.4': '每月奖金将于月底结算后，次月第一周统一发放',
    'process.notice.5': '若出现抄袭、恶意刷分等现象，将被删除全部分数，取消参与资格',
    'process.notice.6': '创作类内容，需要twitter @官方账号',
    'process.social.title': '了解Flipflop：关注以下官方账号并了解更多最新实时动态',
    'login.page.title': '用户登录',
    'login.page.subtitle': '登录 Pathfinders Program 账号',
    'login.form.account': '邮箱/用户名',
    'login.form.password': '密码',
    'login.form.account.placeholder': '请输入邮箱或用户名',
    'login.form.password.placeholder': '请输入密码',
    'login.form.submit': '登录',
    'login.form.register.link': '没有账号？立即注册',
    'register.page.title': '用户注册',
    'register.page.subtitle': '使用邮箱注册 Pathfinders Program 账号',
    'register.form.username': '用户名',
    'register.form.email': '邮箱地址',
    'register.form.password': '密码',
    'register.form.confirm.password': '确认密码',
    'register.form.twitter': '推特账号',
    'register.form.username.placeholder': '请输入用户名',
    'register.form.email.placeholder': '请输入邮箱地址',
    'register.form.password.placeholder': '请输入密码（至少8位）',
    'register.form.confirm.password.placeholder': '请再次输入密码',
    'register.form.twitter.placeholder': '请输入推特用户名（不含@符号）',
    'register.form.submit': '注册',
    'register.form.login.link': '已有账号？立即登录',
    'register.twitter.required': '推特账号为必填项',
    'register.twitter.invalid': '请输入有效的推特用户名',
    'admin.page.title': '管理员后台',
    'admin.page.subtitle': '管理用户和审核表单',
    'admin.tab.forms': '表单审核',
    'admin.tab.users': '用户管理', 
    'admin.tab.stats': '数据统计',
    'admin.forms.title': '待审核表单',
    'admin.table.user': '用户',
    'admin.table.formtype': '表单类型',
    'admin.table.submitdate': '提交日期',
    'admin.table.status': '状态',
    'admin.table.actions': '操作',
    'admin.table.username': '用户名',
    'admin.table.email': '邮箱',
    'admin.table.points': 'Flipprints',
    'admin.table.level': '等级',
    'admin.action.approve': '通过',
    'admin.action.reject': '拒绝',
    'admin.action.edit': '编辑',
    'admin.action.delete': '删除',
    'admin.users.title': '用户列表',
    'admin.stats.title': '数据统计',
    'admin.stats.totalusers': '总用户数',
    'admin.stats.pendingforms': '待审核表单',
    'admin.stats.totalpoints': '总Flipprints',
    'admin.status.pending': '待审核',
    'forms.page.title': '表格申请',
    'forms.page.subtitle': '选择你需要提交的表格类型',
    'forms.application.title': '申请表',
    'forms.application.desc': '提交基本申请信息，开始你的探索之旅',
    'forms.activity.title': '活动申请表',
    'forms.activity.desc': '申请参与特定活动或项目',
    'forms.achievement.title': '成果提交表',
    'forms.achievement.desc': '提交项目成果和完成情况',
    'forms.start.fill': '开始填写',
    'forms.submit.records': '提交记录',
    'forms.submit.records.desc': '登录后可以查看你的表单提交记录和审核状态',
    'forms.view.records': '查看我的提交记录',
    'forms.application.page.title': '申请表',
    'forms.application.page.desc': '填写基本信息，开始你的探索之旅',
    'forms.field.fullname': '姓名',
    'forms.field.age': '年龄',
    'forms.field.occupation': '职业',
    'forms.field.education': '学历',
    'forms.field.experience': '相关经验',
    'forms.field.motivation': '参与动机',
    'forms.field.expectations': '期望收获',
    'forms.field.required': '*',
    'forms.placeholder.select': '请选择',
    'forms.education.highschool': '高中',
    'forms.education.college': '大专',
    'forms.education.bachelor': '本科',
    'forms.education.master': '硕士',
    'forms.education.doctor': '博士',
    'forms.placeholder.experience': '请描述你的相关经验和技能',
    'forms.placeholder.motivation': '为什么想要参与Pathfinders Program？',
    'forms.placeholder.expectations': '希望通过这个项目获得什么？',
    'forms.submit.info': '提交说明',
    'forms.submit.info.1': '审核通过后可获得10-50 Flipprints',
    'forms.submit.info.2': '审核结果将在1-3个工作日内通知',
    'forms.submit.info.3': '每月最多提交3次申请',
    'forms.submit.info.4': '请确保信息真实有效',
    'forms.button.cancel': '取消',
    'forms.button.submit': '提交申请',
    'forms.activity.page.title': '活动申请表',
    'forms.activity.page.desc': '申请参与特定活动或项目',
    'forms.field.activitytype': '活动类型',
    'forms.field.activityname': '活动名称',
    'forms.field.startdate': '开始日期',
    'forms.field.enddate': '结束日期',
    'forms.field.participants': '参与人数',
    'forms.field.description': '活动描述',
    'forms.field.goals': '预期目标',
    'forms.field.requirements': '特殊要求',
    'forms.activity.type.research': '技术研讨',
    'forms.activity.type.development': '项目开发',
    'forms.activity.type.community': '社区活动',
    'forms.activity.type.training': '培训课程',
    'forms.activity.type.other': '其他',
    'forms.placeholder.activityname': '请输入活动名称',
    'forms.placeholder.description': '请详细描述活动内容和安排',
    'forms.placeholder.goals': '希望通过活动达到什么目标？',
    'forms.placeholder.requirements': '是否有特殊需求或要求？',
    'forms.activity.submit.info.1': '活动审核通过后可获得20-100 Flipprints',
    'forms.activity.submit.info.2': '审核结果将在3-5个工作日内通知',
    'forms.activity.submit.info.3': '活动完成后需要提交成果报告',
    'forms.activity.submit.info.4': '请确保活动信息真实可行',
    'forms.achievement.page.title': '成果提交表',
    'forms.achievement.page.desc': '提交项目成果和完成情况',
    'forms.field.projectname': '项目名称',
    'forms.field.completiondate': '完成日期',
    'forms.field.hoursspent': '投入时间(小时)',
    'forms.field.achievements': '主要成果',
    'forms.field.challenges': '遇到的挑战',
    'forms.field.lessons': '经验总结',
    'forms.field.attachments': '相关链接',
    'forms.achievement.type.development': '技术开发',
    'forms.achievement.type.community': '社区贡献',
    'forms.achievement.type.content': '内容创作',
    'forms.achievement.type.organization': '活动组织',
    'forms.placeholder.projectname': '请输入项目名称',
    'forms.placeholder.achievements': '请详细描述项目完成的主要成果和产出',
    'forms.placeholder.challenges': '在项目过程中遇到了哪些挑战？如何解决的？',
    'forms.placeholder.lessons': '从这次项目中获得了哪些经验和教训？',
    'forms.placeholder.attachments': '请输入GitHub链接、演示地址等',
    'forms.achievement.submit.info.1': '成果审核通过后可获得30-150积分',
    'forms.achievement.submit.info.2': '审核结果将在5-7个工作日内通知',
    'forms.achievement.submit.info.3': '请提供详细的项目描述和成果证明',
    'forms.achievement.submit.info.4': '高质量的成果可能获得额外奖励',
    'forms.button.submit.achievement': '提交成果',
    'admin.sample.username1': '张三',
    'admin.sample.username2': '李四',
    'admin.sample.username3': '王五',
    'admin.sample.formtype.application': '申请表',
    'admin.sample.formtype.activity': '活动申请表',
    'admin.sample.formtype.achievement': '成果提交表',
    'admin.sample.level.bronze': '青铜',
    'admin.sample.level.silver': '白银',
    'admin.sample.level.gold': '黄金',
    'profile.page.title': '个人中心',
    'profile.basic.info': '基本信息',
    'profile.username': '用户名',
    'profile.email': '邮箱',
    'profile.user.title': '称号',
    'profile.monthly.points': '当月Flipprints',
    'profile.total.points': '总Flipprints',
    'profile.wallet': '钱包地址',
    'profile.edit.info': '编辑信息',
    'profile.change.password': '修改密码',
    'profile.reward.history': '奖励历史',
    'profile.submission.records': '提交记录',
    'profile.continue.submit': '继续提交表单 →',
    'profile.title.explorer': '探险者',
    'profile.title.pathfinder': '探路者',
    'profile.title.trailblazer': '开路者',
    'profile.title.pioneer': '先驱者',
    'profile.reward.date': '日期',
    'profile.reward.type': '奖励类型',
    'profile.reward.amount': '金额',
    'profile.reward.status': '状态',
    'date.format': 'YYYY年MM月DD日',
    // Pathfinders benefits section
    'home.pathfinders.title': '成为Pathfinders，你将获得什么？',
    'home.pathfinders.subtitle': '通过贡献积累「Flipprints」（👣脚印），晋升不同等级，获得专属荣誉与特权',
    'home.pathfinders.benefits.flipprints.title': 'Flipprints 👣积分荣誉体系',
    'home.pathfinders.benefits.flipprints.desc1': '每一份贡献都会化为"脚印"留在 Flipflop 的生态里',
    'home.pathfinders.benefits.flipprints.desc2': '实时更新的Flipprints排行榜，激励你不断前行',
    'home.pathfinders.benefits.rewards.title': '丰厚激励与专属奖励',
    'home.pathfinders.benefits.rewards.desc1': '完成基础任务即可获得 10U 基础奖励',
    'home.pathfinders.benefits.rewards.desc2': '优秀贡献者可获得 50U – 500U 的高阶奖励',
    'home.pathfinders.benefits.funding.title': '创业与融资支持',
    'home.pathfinders.benefits.funding.desc1': '核心成员将获得创业指导、资源对接等全方位支持',
    'home.pathfinders.benefits.funding.desc2': '有机会接触到优质的孵化器、投资人和合作伙伴',
    'home.pathfinders.benefits.launchpad.title': 'Launchpad 特权',
    'home.pathfinders.benefits.launchpad.desc1': '核心Pathfinders可优先接触平台即将孵化的项目，参与测试、AMA、战略讨论',
    'home.pathfinders.benefits.launchpad.desc2': '享有和项目方、投资人直接交流的机会，真正走到生态建设的前沿',
    'home.pathfinders.benefits.nft.title': 'Ambassador NFT 身份徽章',
    'home.pathfinders.benefits.nft.desc1': '特定级别将获得荣誉 Pathfinders NFT，作为不可替代的荣誉象征',
    'home.pathfinders.benefits.nft.desc2': 'NFT 将成为你在 Flipflop 社区身份的数字凭证，永久铭刻你的贡献',
    'home.pathfinders.benefits.community.title': '社区影响力与共建权',
    'home.pathfinders.benefits.community.desc1': '每一位参与者都有机会出现在官网、Pathfinders榜单和官方Space中，获得更多曝光',
    'home.pathfinders.benefits.community.desc2': '核心成员将直接参与Flipflop的战略讨论，共同决定生态的未来方向',
    'home.pathfinders.benefits.flipprints.title': 'Flipprints 👣积分荣誉体系',
    'home.pathfinders.benefits.flipprints.desc1': '每一份贡献都会化为"脚印"留在 Flipflop 的生态里',
    'home.pathfinders.benefits.flipprints.desc2': '实时更新的Flipprints排行榜，激励你不断前行',
    'home.pathfinders.benefits.rewards.title': '丰厚激励与专属奖励',
    'home.pathfinders.benefits.rewards.desc1': '完成基础任务即可获得 10U 基础奖励',
    'home.pathfinders.benefits.rewards.desc2': '优秀贡献者可获得 50U – 500U 的高阶奖励',
    'home.pathfinders.benefits.funding.title': '创业与融资支持',
    'home.pathfinders.benefits.funding.desc1': '核心成员将获得创业指导、资源对接等全方位支持',
    'home.pathfinders.benefits.funding.desc2': '有机会接触到优质的孵化器、投资人和合作伙伴',
    'home.pathfinders.benefits.launchpad.title': 'Launchpad 特权',
    'home.pathfinders.benefits.launchpad.desc1': '核心Pathfinders可优先接触平台即将孵化的项目，参与测试、AMA、战略讨论',
    'home.pathfinders.benefits.launchpad.desc2': '享有和项目方、投资人直接交流的机会，真正走到生态建设的前沿',
    'home.pathfinders.benefits.nft.title': 'Ambassador NFT 身份徽章',
    'home.pathfinders.benefits.nft.desc1': '特定级别将获得荣誉 Pathfinders NFT，作为不可替代的荣誉象征',
    'home.pathfinders.benefits.nft.desc2': 'NFT 将成为你在 Flipflop 社区身份的数字凭证，永久铭刻你的贡献',
    'home.pathfinders.benefits.community.title': '社区影响力与共建权',
    'home.pathfinders.benefits.community.desc1': '每一位参与者都有机会出现在官网、Pathfinders榜单和官方Space中，获得更多曝光',
    'home.pathfinders.benefits.community.desc2': '核心成员将直接参与Flipflop的战略讨论，共同决定生态的未来方向',
    // Forms translations
    'forms.application.title': 'Pathfinders申请表',
    'forms.achievement.title': '成果提交表',
    'forms.activity.title': '活动组织申请表',
    'forms.required': '*',
    'forms.optional.note': '备注：加*的问题为必填项，其余为选填',
    'forms.submit.button': '提交申请',
    'forms.cancel.button': '取消',
    'forms.submit.achievement': '提交成果',
    // Common form fields
    'forms.field.name': '姓名',
    'forms.field.email': '邮箱',
    'forms.field.twitter': 'Twitter/X用户名',
    'forms.field.telegram': 'Telegram用户名',
    'forms.field.wallet': '钱包地址',
    'forms.field.wallet.solana': '钱包地址（Solana）',
    'forms.field.wallet.both': '钱包地址（Solana, USDT）',
    // Application form specific
    'forms.application.web3role': '在Web3的参与身份',
    'forms.application.expertise': '擅长方向',
    'forms.application.portfolio': '代表作品/过往贡献链接（如有，请附上）',
    'forms.application.motivation': '你为什么想加入 Pathfinders',
    'forms.application.weeklyhours': '每周可投入时间（小时数或大致频率）',
    'forms.application.events': '是否愿意参与线下/线上活动组织',
    'forms.application.resources': '是否有资源或渠道支持 Flipflop（如媒体、KOL、社区）',
    'forms.application.entrepreneurship': '是否有创业想法/孵化需求',
    // Web3 roles
    'forms.role.entrepreneur': '创业者',
    'forms.role.developer': '开发者',
    'forms.role.creator': '内容创作者',
    'forms.role.kol': 'KOL',
    'forms.role.community': '社区建设者',
    'forms.role.marketing': '运营/市场',
    'forms.role.researcher': '研究员',
    'forms.role.enthusiast': '爱好者',
    'forms.role.student': '学生',
    // Expertise areas
    'forms.expertise.content': '内容创作',
    'forms.expertise.community': '社群活动',
    'forms.expertise.research': '研究写作',
    'forms.expertise.promotion': '推广传播',
    // Achievement form specific
    'forms.achievement.category': '提交类别',
    'forms.achievement.tasktype': '具体任务类型',
    'forms.achievement.contentlink': '内容链接',
    'forms.achievement.screenshot': '截图证明（可上传文件）',
    'forms.achievement.completion': '完成日期',
    'forms.achievement.description': '简短说明（如内容亮点/传播效果）',
    // Categories
    'forms.category.promotion': '传播类',
    'forms.category.creation': '创作类',
    'forms.category.community': '社群类',
    // Task types
    'forms.task.like': '+0.5 X 官方内容一键三联（转发+点赞+评论）',
    'forms.task.content': '+2 原创内容/ Meme / 平台图文教程',
    'forms.task.article': '+8-10 长篇或深度文章 / 机制理解与应用 (不少于500字)',
    'forms.task.video': '+12-15 短视频（不少于30秒）',
    'forms.task.ama': '+2-3 参加AMA / 线上活动，提问或参与讨论',
    'forms.task.recap': '+8-10 AMA Recap（不少于500字）',
    'forms.task.telegram': '+2–3 Telegram参与话题讨论',
    'forms.task.offline': '+25-30 成功组织一场官方认证线下活动',
    // Activity form specific
    'forms.activity.organizer': '组织人',
    'forms.activity.type': '活动类型',
    'forms.activity.theme': '活动主题',
    'forms.activity.introduction': '简要介绍',
    'forms.activity.time': '活动时间',
    'forms.activity.location': '活动地点',
    'forms.activity.scale': '活动规模',
    'forms.activity.goals': '活动目标',
    'forms.activity.audience': '目标受众',
    'forms.activity.process': '活动流程',
    'forms.activity.financial': '需要FlipFlop提供的资金支持及具体说明（最好可以逐项说明支出）',
    'forms.activity.support': '需要FlipFlop提供的其他支持',
    'forms.activity.speakers': '拟邀讲师或发言人（如有）',
    'forms.activity.partners': '合作伙伴（如联合社区/KOL）',
    'forms.activity.results': '预期成果（人数、传播量、媒体覆盖等）',
    // Activity types
    'forms.acttype.online': '线上',
    'forms.acttype.offline': '线下',
    'forms.acttype.hybrid': '线上+线下',
    // Target audience
    'forms.audience.newusers': '新用户',
    'forms.audience.community': '社区/KOL',
    'forms.audience.projects': '项目方',
    'forms.audience.makers': '做市商',
    // Placeholders
    'forms.placeholder.username': '@username',
    'forms.placeholder.portfolio': '请提供您的代表作品或过往贡献的链接',
    'forms.placeholder.motivation': '请描述您加入 Pathfinders 的动机和期望',
    'forms.placeholder.weeklyhours': '例如：10小时/周 或 每天2小时',
    'forms.placeholder.events': '是/否，以及具体想法',
    'forms.placeholder.resources': '请描述您可以提供的资源或渠道',
    'forms.placeholder.entrepreneurship': '请描述您的创业想法或孵化需求',
    'forms.placeholder.contentlink': '请提供相关内容的链接',
    'forms.placeholder.description': '请简述内容亮点或传播效果',
    'forms.placeholder.location': '具体地址或在线平台',
    'forms.placeholder.scale': '预计参与人数',
    'forms.placeholder.introduction': '请简要介绍活动内容和目的',
    'forms.placeholder.goals': '请描述活动预期达成的目标',
    'forms.placeholder.process': '请详细描述活动的时间安排和流程',
    'forms.placeholder.financial': '请详细列出所需资金支持和用途',
    'forms.placeholder.support': '如技术支持、宣传推广、讲师推荐等',
    'forms.placeholder.speakers': '请提供讲师姓名和背景',
    'forms.placeholder.partners': '请列出合作伙伴信息',
    'forms.placeholder.results': '请描述预期的活动效果和成果',
    // File upload
    'forms.upload.text': '上传文件',
    'forms.upload.drag': '或拖拽到此处',
    'forms.upload.format': 'PNG, JPG, GIF 最大 10MB'
  },
  en: {
    'home.title': 'Flipflop Pathfinders',
    'home.hero.title': '👣 Welcome to Flipflop Pathfinders Program',
    'home.subtitle': 'A community tailored for partners who love Flipflop and Web3 innovation, committed to promoting a fair, just, and community-driven Launchpad ecosystem.',
    'home.join': 'Join Now',
    'home.learn': 'Learn Process',
    'home.description': 'We adopt Proof of Mint (PoM) and URC recommendation mechanisms to encourage builders, creators, and promoters to inject vitality into new projects, leaving their own footprints through content, activities, and collaborations. Here, you can find like-minded partners and witness the growth process of projects from Mint to graduation into external markets. Flipflop is not just a token issuance platform, but an open creative stage that allows more ideas to be implemented and achieve growth from zero to one!',
    'home.features.builder.title': 'Builder Incentives',
    'home.features.builder.desc': 'Inject vitality into projects',
    'home.features.community.title': 'Community Collaboration',
    'home.features.community.desc': 'Like-minded partners',
    'home.features.growth.title': 'Zero to One',
    'home.features.growth.desc': 'Ideas come to life',
    'home.mission.title': '🎯 Goals of Flipflop Pathfinders Program',
    'home.mission.community': 'Expand Flipflop\'s global community influence through content creation and activities',
    'home.mission.incubation': 'Accompany new projects through incubation, driving Web3 entrepreneurs from zero to one',
    'home.mission.rewards': 'Provide rewards, merchandise, and entrepreneurial support for outstanding contributors',
    'home.mission.builder': 'Build a free, open, and mutually supportive builder community',
    'home.mission.footprints': 'Let every participant leave their footprints in the Flipflop ecosystem',
    'home.mission.quote': '"Join the community, leave your footprints, and become a co-builder shaping the future of Web3 entrepreneurship"',
    'home.features.honor.title': 'Honor System',
    'home.features.honor.desc': 'Flipprints 👣 points honor system, every contribution becomes "footprints" in the Flipflop ecosystem',
    'home.features.ranking.desc': 'Real-time updated points leaderboard to motivate your continuous progress',
    'home.features.forms.desc': 'Multiple application forms with online submission and review support',
    'home.social.title': 'Follow Us!',
    'home.social.desc': 'Flipflop will publish the latest activities and related ecosystem progress.',
    'home.social.global': 'Global Community',
    'home.social.chinese': 'Chinese Community',
    'honor.title': 'Honor System',
    'honor.subtitle': 'Accumulate "Flipprints" (👣 footprints) through contributions, advance to the following different levels, and gain exclusive honors and privileges.',
    'ranking.title': 'Ranking',
    'ranking.subtitle': 'Real-time user points ranking',
    'process.title': 'Process',
    'process.subtitle': 'Learn how to participate in Pathfinders Program',
    'forms.title': 'Forms',
    'forms.subtitle': 'Select the form type you need to submit',
    'login.title': 'Login',
    'register.title': 'Register',
    'profile.title': 'Profile',
    'admin.title': 'Admin Panel',
    'theme.toggle': 'Toggle Theme',
    'language.toggle': 'Toggle Language',
    'user.welcome': 'Welcome',
    'user.logout': 'Logout',
    'honor.page.title': '✨ What will you get as a Pathfinder?',
    'honor.page.subtitle': 'Accumulate "Flipprints" (👣 footprints) through contributions, advance to different levels, and gain exclusive honors and privileges',
    'honor.level.l1': 'L1 Explorer',
    'honor.level.l2': 'L2 Pathfinder',
    'honor.level.l3': 'L3 Trailblazer',
    'honor.level.l4': 'L4 Pioneer',
    'honor.benefits': 'Benefits:',
    'honor.monthly.title': '💡 Monthly Incentives',
    'honor.monthly.subtitle': 'Every Pathfinders member who completes the monthly basic task list will receive a 10U basic reward.',
    'honor.table.completion': 'Completion Status',
    'honor.table.reward': 'Reward Amount',
    'honor.table.requirements': 'Specific Task Requirements',
    'honor.flipprints.title': '🔗 Flipprints Contribution Reference',
    'honor.table.category': 'Category',
    'honor.table.task': 'Task Type',
    'honor.table.points': 'Points Range',
    'honor.table.notes': 'Notes',
    'honor.notice.title': 'Important Notes',
    'honor.notice.1': 'Monthly points cap: 50 points, excess points will not be counted in the leaderboard',
    'honor.notice.2': 'Points will be compiled every Sunday and updated on the leaderboard',
    'honor.notice.3': 'Monthly bonuses will be distributed in the first week of the following month after settlement',
    'honor.notice.4': 'Level accumulation will not be reset, every footprint is a mark of your growth with Flipflop',
    // Honor level benefits
    'honor.l1.benefit.1': 'Get Explorer community identity badge (community title)',
    'honor.l1.benefit.2': 'Join Pathfinders exclusive channel (Telegram)',
    'honor.l1.benefit.3': 'Priority access to official platform news and task notifications',
    'honor.l1.benefit.4': 'Get irregular benefits and airdrop participation eligibility',
    'honor.l2.benefit.1': 'Get Pathfinder identity badge (community title)',
    'honor.l2.benefit.2': 'Eligible for Flipflop custom merchandise (T-shirt/sticker pack) lottery',
    'honor.l2.benefit.3': 'Participate in monthly online closed-door sharing sessions (learning ecosystem trends/case studies)',
    'honor.l2.benefit.4': 'Opportunity to join small-scale offline workshops or study tours',
    'honor.l3.benefit.1': 'Priority to become AMA/online event guest or co-host',
    'honor.l3.benefit.2': 'Awarded Flipflop community Trailblazer title, can be displayed on X homepage',
    'honor.l3.benefit.3': 'Get early testing qualification for Flipflop ecosystem projects (beta whitelist)',
    'honor.l3.benefit.4': 'Get resource library access (investment research materials, presentation PPTs, learning manuals)',
    'honor.l3.benefit.5': 'Quarterly closed-door discussion with core team',
    'honor.l4.benefit.1': 'Get limited merchandise gift pack and honorary NFT',
    'honor.l4.benefit.2': 'Listed on Flipflop honor roll, permanently displayed',
    'honor.l4.benefit.3': 'Direct participation in platform strategic discussions (roadmap suggestions, product beta priority)',
    'honor.l4.benefit.4': 'Get entrepreneurial support channel (introduction to incubators/funds, initial connections)',
    'honor.l4.benefit.5': 'Get long-term cooperation opportunities (as community partner/event co-organizer)',
    // Monthly incentive table
    'honor.monthly.basic.completion': 'Basic Task Completion',
    'honor.monthly.basic.reward': '10U/month',
    'honor.monthly.basic.requirements': 'Promotion: ≥1 "one-click triple" (retweet+like+comment) per week, ≥4 per month\nCreation: At least 2 original content per month (Meme/tweet/tutorial optional)\nCommunity: Participate in ≥1 community interaction (as speaker Q&A/sharing in AMA, or Telegram topic discussion)',
    'honor.monthly.advanced1.completion': 'Advanced I',
    'honor.monthly.advanced1.reward': '50U/month',
    'honor.monthly.advanced1.requirements': 'Promotion: ≥8 "one-click triple"\nCreation: ≥4 original content (may include short videos/graphic tutorials)\nCommunity: ≥2 community interactions',
    'honor.monthly.advanced2.completion': 'Advanced II',
    'honor.monthly.advanced2.reward': '100U/month',
    'honor.monthly.advanced2.requirements': 'Promotion: ≥10 "one-click triple"\nCreation: ≥8 original content (at least 1 long article 500+ words or 1 original short video)\nCommunity: ≥3 community interactions',
    'honor.monthly.advanced3.completion': 'Advanced III',
    'honor.monthly.advanced3.reward': '200U/month',
    'honor.monthly.advanced3.requirements': 'Promotion: ≥12 "one-click triple"\nCreation: ≥12 original content (at least 2 long articles 500+ words or 2 original videos)\nCommunity: ≥4 community interactions (at least 1 AMA Recap 500+ words)',
    'honor.monthly.special.completion': 'Special Reward',
    'honor.monthly.special.reward': '500U/month',
    'honor.monthly.special.requirements': 'Meet all Advanced III requirements plus\nAdditional contributions, ≥1 item including:\n1. Viral content (high-spread articles/videos/Memes)\n2. Successfully organize large events (AMA, Space, Meetup)\n3. Introduce key cooperation resources to Flipflop',
    'honor.monthly.special.note': 'If you need to organize activities, you can apply in advance here, including related funding and requirements',
    'honor.monthly.special.link': 'Activity Application Form',
    'honor.monthly.definitions.title': 'Please note the following details when participating in monthly incentive activities:',
    'honor.monthly.definitions.promotion': 'Promotion "one-click triple": Retweet, like, and comment on the same official announcement/activity content on X',
    'honor.monthly.definitions.creation': 'Creative content: Any original content published on X must @ official account and #FFPP',
    'honor.monthly.definitions.official.link': 'https://x.com/flipfloplaunch',
    'honor.monthly.definitions.community': 'Community interaction: Including participating in community online activities or AMA as speaker Q&A/sharing, or Telegram topic discussions with effective communication and screenshot evidence',
    'honor.flipprints.submit.note': 'After completing tasks, please be sure to take screenshots and submit them through',
    'honor.flipprints.submit.link': 'Achievement Submission Form',
    'honor.flipprints.submit.text': 'for unified submission',
    'honor.notice.5': 'Basic rewards and advanced rewards are not cumulative',
    'honor.warning.title': 'Important Warning',
    'honor.warning.text': 'Note: If plagiarism or malicious point farming occurs, all points will be deleted, monthly rewards will not be issued, and participation in Flipflop activities will be permanently banned',
    // Flipprints contribution table
    'honor.flipprints.promotion.category': 'Promotion',
    'honor.flipprints.promotion.task': 'X official content one-click triple',
    'honor.flipprints.promotion.points': '+0.5',
    'honor.flipprints.promotion.notes': 'Simple retweet/like not counted',
    'honor.flipprints.creation.category': 'Creation',
    'honor.flipprints.creation.task1': 'Original content/Meme/Platform tutorial',
    'honor.flipprints.creation.points1': '+2',
    'honor.flipprints.creation.notes1': 'Monthly points cap: 10 points',
    'honor.flipprints.creation.task2': 'Long or in-depth article (at least 500 words)',
    'honor.flipprints.creation.points2': '+8-10',
    'honor.flipprints.creation.notes2': 'Emphasis on originality',
    'honor.flipprints.creation.task3': 'Short video (at least 30 seconds)',
    'honor.flipprints.creation.points3': '+12-15',
    'honor.flipprints.creation.notes3': 'Emphasis on originality, semi-original points halved',
    'honor.flipprints.community.category': 'Community',
    'honor.flipprints.community.task1': 'Participate in AMA/online activities, ask questions or participate in discussions',
    'honor.flipprints.community.points1': '+2-3',
    'honor.flipprints.community.notes1': 'Need to speak as Speaker',
    'honor.flipprints.community.task2': 'AMA Recap (at least 500 words)',
    'honor.flipprints.community.points2': '+8-10',
    'honor.flipprints.community.notes2': 'Published on Twitter and @official account',
    'honor.flipprints.community.task3': 'Successfully organize an officially certified offline event',
    'honor.flipprints.community.points3': '+25-30',
    'honor.flipprints.community.notes3': 'High investment task, single high score',
    'honor.flipprints.viral.category': 'Viral Content',
    'honor.flipprints.viral.task': 'Any original content gains widespread attention',
    'honor.flipprints.viral.points': '×1.5–3x',
    'honor.flipprints.viral.notes': 'Additional rewards for viral content',
    // Ranking page
    'ranking.page.title': 'Points Leaderboard',
    'ranking.page.subtitle': 'Real-time updated user points ranking',
    'ranking.top10.title': 'Top 10 Users',
    'ranking.table.rank': 'Rank',
    'ranking.table.username': 'Username',
    'ranking.table.points': 'Points',
    'ranking.table.level': 'Level',
    'ranking.points.unit': ' pts',
    'ranking.myrank.title': 'My Ranking',
    'ranking.myrank.rank': 'Rank',
    'ranking.myrank.points': 'Points',
    'ranking.myrank.level': 'Level',
    'ranking.myrank.completion': 'Completion',
    'ranking.currentuser': 'Current User',
    'ranking.improve.link': 'Improve ranking, submit forms now →',
    'ranking.level.diamond': 'Diamond',
    'ranking.level.platinum': 'Platinum',
    'ranking.level.gold': 'Gold',
    'ranking.level.silver': 'Silver',
    'ranking.level.bronze': 'Bronze',
    'ranking.table.twitter': 'Twitter',
    'ranking.total.points': 'Total Points',
    'ranking.reference.note': 'For detailed points calculation, please refer to',
    'ranking.reference.link': 'Honor System',
    // Process page
    'process.page.title': '🌟 How to Participate in Flipflop Pathfinders Program?',
    'process.page.subtitle': 'Learn how to participate in Pathfinders Program',
    'process.step1.title': 'Apply to Join',
    'process.step1.description': 'Fill out the "Official Application Form" and provide your basic information (nickname, social accounts, wallet address)',
    'process.step1.detail1': 'Tell us your areas of expertise (content creation / community activities / research writing / promotion)',
    'process.step1.detail2': 'Showcase some representative works',
    'process.step1.detail3': 'A brief self-introduction explaining why you want to join Pathfinders',
    'process.step1.detail4': 'After approval, you will be invited to join the exclusive community',
    'process.step2.title': 'Complete Tasks, Accumulate Footprints',
    'process.step2.description': 'Basic tasks (unlock monthly reward eligibility) and advanced tasks (compete for high rewards)',
    'process.step2.detail1': 'Basic tasks: Like/retweet/comment on official content weekly',
    'process.step2.detail2': 'Creative expression: Publish 2 original content pieces monthly (Memes, short tweets, or tutorials)',
    'process.step2.detail3': 'Community building: Participate in at least 1 AMA/Telegram discussion monthly',
    'process.step2.detail4': 'Advanced tasks: Write in-depth articles, create videos, organize events',
    'process.step3.title': 'Submit Results',
    'process.step3.description': 'All task results need to be uploaded through "Submission Forms"',
    'process.step3.detail1': 'Include: task type, content links, screenshot proof, wallet address',
    'process.step3.detail2': 'Daily content can be submitted anytime, recommended weekly',
    'process.step3.detail3': 'Monthly summary submission must be completed before month end',
    'process.step3.detail4': 'All submitted content will be reviewed and scored',
    'process.step4.title': 'Review and Leaderboard',
    'process.step4.description': 'Pathfinders Program operations team will review and score from four dimensions',
    'process.step4.detail1': 'Content quality: originality, depth, value',
    'process.step4.detail2': 'Influence: readership, engagement, reach',
    'process.step4.detail3': 'Community value: contribution to community building',
    'process.step4.detail4': 'Completion: quality and timeliness of task completion',
    'process.step5.title': 'Receive Rewards',
    'process.step5.description': 'Complete basic tasks to receive 10U basic reward; outstanding contributors can receive 50U – 500U advanced rewards',
    'process.step5.detail1': 'All rewards will be distributed securely on-chain (Solana address / USDT)',
    'process.step5.detail2': 'Weekly leaderboard updates publicly, transparent and fair',
    'process.step5.detail3': 'Your footprints represent not only rewards, but your growth journey in the Flipflop community',
    'process.step5.detail4': 'Enjoy corresponding benefits and privileges after level upgrades',
    'process.step6.title': 'Continuous Growth',
    'process.step6.description': 'Leave your footprints with global partners and shape the future of Web3',
    'process.step6.detail1': 'Accumulate Flipprints 👣 to upgrade levels',
    'process.step6.detail2': 'Unlock more benefits and cooperation opportunities',
    'process.step6.detail3': 'Become a core builder of the Flipflop ecosystem',
    'process.step6.detail4': 'Enjoy entrepreneurial support and funding connection opportunities',
    'process.details.title': 'Details:',
    'process.register.link': 'Register Now →',
    'process.forms.link': 'Start Filling Application Form →',
    'process.application.form': 'Official Application Form',
    'process.achievement.form': 'Achievement Submission Form',
    'process.activity.form': 'Activity Application Form',
    'process.notice.title': 'Important Notes',
    'process.notice.1': 'After completing tasks, please take screenshots and submit through the achievement submission form',
    'process.notice.2': 'Monthly points cap: 50 points, excess points will not be counted in the leaderboard',
    'process.notice.3': 'Points will be compiled every Sunday and updated on the leaderboard',
    'process.notice.4': 'Monthly bonuses will be distributed in the first week of the following month after settlement',
    'process.notice.5': 'Plagiarism or malicious point farming will result in deletion of all points and disqualification',
    'process.notice.6': 'Creative content must @official account on Twitter',
    'process.social.title': 'Learn about Flipflop: Follow official accounts below for latest updates',
    'login.page.title': 'User Login',
    'login.page.subtitle': 'Login to your Pathfinders Program account',
    'login.form.account': 'Email/Username',
    'login.form.password': 'Password',
    'login.form.account.placeholder': 'Enter your email or username',
    'login.form.password.placeholder': 'Enter your password',
    'login.form.submit': 'Login',
    'login.form.register.link': 'Don\'t have an account? Register now',
    'register.page.title': 'User Registration',
    'register.page.subtitle': 'Register your Pathfinders Program account with email',
    'register.form.username': 'Username',
    'register.form.email': 'Email Address',
    'register.form.password': 'Password',
    'register.form.confirm.password': 'Confirm Password',
    'register.form.twitter': 'Twitter Handle',
    'register.form.username.placeholder': 'Enter your username',
    'register.form.email.placeholder': 'Enter your email address',
    'register.form.password.placeholder': 'Enter password (at least 8 characters)',
    'register.form.confirm.password.placeholder': 'Enter password again',
    'register.form.twitter.placeholder': 'Enter Twitter username (without @ symbol)',
    'register.form.submit': 'Register',
    'register.form.login.link': 'Already have an account? Login now',
    'register.twitter.required': 'Twitter handle is required',
    'register.twitter.invalid': 'Please enter a valid Twitter username',
    'admin.page.title': 'Admin Panel',
    'admin.page.subtitle': 'Manage users and review forms',
    'admin.tab.forms': 'Form Review',
    'admin.tab.users': 'User Management', 
    'admin.tab.stats': 'Statistics',
    'admin.forms.title': 'Pending Forms',
    'admin.table.user': 'User',
    'admin.table.formtype': 'Form Type',
    'admin.table.submitdate': 'Submit Date',
    'admin.table.status': 'Status',
    'admin.table.actions': 'Actions',
    'admin.table.username': 'Username',
    'admin.table.email': 'Email',
    'admin.table.points': 'Points',
    'admin.table.level': 'Level',
    'admin.action.approve': 'Approve',
    'admin.action.reject': 'Reject',
    'admin.action.edit': 'Edit',
    'admin.action.delete': 'Delete',
    'admin.users.title': 'User List',
    'admin.stats.title': 'Statistics',
    'admin.stats.totalusers': 'Total Users',
    'admin.stats.pendingforms': 'Pending Forms',
    'admin.stats.totalpoints': 'Total Points',
    'admin.status.pending': 'Pending',
    'forms.page.title': 'Forms',
    'forms.page.subtitle': 'Select the form type you need to submit',
    'forms.application.title': 'Application Form',
    'forms.application.desc': 'Submit basic application information to start your exploration journey',
    'forms.activity.title': 'Activity Application Form',
    'forms.activity.desc': 'Apply to participate in specific activities or projects',
    'forms.achievement.title': 'Achievement Submission Form',
    'forms.achievement.desc': 'Submit project results and completion status',
    'forms.start.fill': 'Start Filling',
    'forms.submit.records': 'Submission Records',
    'forms.submit.records.desc': 'After logging in, you can view your form submission records and review status',
    'forms.view.records': 'View My Submission Records',
    'forms.application.page.title': 'Application Form',
    'forms.application.page.desc': 'Fill in basic information to start your exploration journey',
    'forms.field.fullname': 'Full Name',
    'forms.field.age': 'Age',
    'forms.field.occupation': 'Occupation',
    'forms.field.education': 'Education',
    'forms.field.experience': 'Relevant Experience',
    'forms.field.motivation': 'Motivation',
    'forms.field.expectations': 'Expectations',
    'forms.field.required': '*',
    'forms.placeholder.select': 'Please select',
    'forms.education.highschool': 'High School',
    'forms.education.college': 'College',
    'forms.education.bachelor': 'Bachelor',
    'forms.education.master': 'Master',
    'forms.education.doctor': 'PhD',
    'forms.placeholder.experience': 'Please describe your relevant experience and skills',
    'forms.placeholder.motivation': 'Why do you want to participate in the Pathfinders Program?',
    'forms.placeholder.expectations': 'What do you hope to gain from this project?',
    'forms.submit.info': 'Submission Information',
    'forms.submit.info.1': '10-50 points can be earned after approval',
    'forms.submit.info.2': 'Review results will be notified within 1-3 business days',
    'forms.submit.info.3': 'Maximum 3 applications per month',
    'forms.submit.info.4': 'Please ensure information is true and valid',
    'forms.button.cancel': 'Cancel',
    'forms.button.submit': 'Submit Application',
    'forms.activity.page.title': 'Activity Application Form',
    'forms.activity.page.desc': 'Apply to participate in specific activities or projects',
    'forms.field.activitytype': 'Activity Type',
    'forms.field.activityname': 'Activity Name',
    'forms.field.startdate': 'Start Date',
    'forms.field.enddate': 'End Date',
    'forms.field.participants': 'Participants',
    'forms.field.description': 'Activity Description',
    'forms.field.goals': 'Expected Goals',
    'forms.field.requirements': 'Special Requirements',
    'forms.activity.type.research': 'Technical Research',
    'forms.activity.type.development': 'Project Development',
    'forms.activity.type.community': 'Community Activity',
    'forms.activity.type.training': 'Training Course',
    'forms.activity.type.other': 'Other',
    'forms.placeholder.activityname': 'Please enter activity name',
    'forms.placeholder.description': 'Please describe the activity content and arrangements in detail',
    'forms.placeholder.goals': 'What goals do you hope to achieve through the activity?',
    'forms.placeholder.requirements': 'Are there any special needs or requirements?',
    'forms.activity.submit.info.1': '20-100 points can be earned after activity approval',
    'forms.activity.submit.info.2': 'Review results will be notified within 3-5 business days',
    'forms.activity.submit.info.3': 'A results report needs to be submitted after activity completion',
    'forms.activity.submit.info.4': 'Please ensure activity information is true and feasible',
    'forms.achievement.page.title': 'Achievement Submission Form',
    'forms.achievement.page.desc': 'Submit project results and completion status',
    'forms.field.projectname': 'Project Name',
    'forms.field.completiondate': 'Completion Date',
    'forms.field.hoursspent': 'Hours Spent',
    'forms.field.achievements': 'Main Achievements',
    'forms.field.challenges': 'Challenges Encountered',
    'forms.field.lessons': 'Lessons Learned',
    'forms.field.attachments': 'Related Links',
    'forms.achievement.type.development': 'Technical Development',
    'forms.achievement.type.community': 'Community Contribution',
    'forms.achievement.type.content': 'Content Creation',
    'forms.achievement.type.organization': 'Event Organization',
    'forms.placeholder.projectname': 'Please enter project name',
    'forms.placeholder.achievements': 'Please describe in detail the main achievements and outputs of the project',
    'forms.placeholder.challenges': 'What challenges were encountered during the project? How were they resolved?',
    'forms.placeholder.lessons': 'What experience and lessons were gained from this project?',
    'forms.placeholder.attachments': 'Please enter GitHub links, demo addresses, etc.',
    'forms.achievement.submit.info.1': '30-150 points can be earned after achievement approval',
    'forms.achievement.submit.info.2': 'Review results will be notified within 5-7 business days',
    'forms.achievement.submit.info.3': 'Please provide detailed project description and achievement proof',
    'forms.achievement.submit.info.4': 'High-quality achievements may receive additional rewards',
    'forms.button.submit.achievement': 'Submit Achievement',
    'admin.sample.username1': 'John Smith',
    'admin.sample.username2': 'Lisa Johnson',
    'admin.sample.username3': 'Michael Brown',
    'admin.sample.formtype.application': 'Application Form',
    'admin.sample.formtype.activity': 'Activity Application',
    'admin.sample.formtype.achievement': 'Achievement Submission',
    'admin.sample.level.bronze': 'Bronze',
    'admin.sample.level.silver': 'Silver',
    'admin.sample.level.gold': 'Gold',
    'profile.page.title': 'Profile',
    'profile.basic.info': 'Basic Information',
    'profile.username': 'Username',
    'profile.email': 'Email',
    'profile.user.title': 'Title',
    'profile.monthly.points': 'Monthly Flipprints',
    'profile.total.points': 'Total Flipprints',
    'profile.wallet': 'Wallet Address',
    'profile.edit.info': 'Edit Information',
    'profile.change.password': 'Change Password',
    'profile.reward.history': 'Reward History',
    'profile.submission.records': 'Submission Records',
    'profile.continue.submit': 'Continue Submitting Forms →',
    'profile.title.explorer': 'Explorer',
    'profile.title.pathfinder': 'Pathfinder',
    'profile.title.trailblazer': 'Trailblazer',
    'profile.title.pioneer': 'Pioneer',
    'profile.reward.date': 'Date',
    'profile.reward.type': 'Reward Type',
    'profile.reward.amount': 'Amount',
    'profile.reward.status': 'Status',
    'date.format': 'MM/DD/YYYY',
    // Pathfinders benefits section
    'home.pathfinders.title': 'What Will You Get as a Pathfinder?',
    'home.pathfinders.subtitle': 'Accumulate "Flipprints" (👣 footprints) through contributions, advance to different levels, and gain exclusive honors and privileges',
    'home.pathfinders.benefits.flipprints.title': 'Flipprints 👣 Honor System',
    'home.pathfinders.benefits.flipprints.desc1': 'Every contribution becomes "footprints" in the Flipflop ecosystem',
    'home.pathfinders.benefits.flipprints.desc2': 'Real-time updated Flipprints leaderboard to motivate your continuous progress',
    'home.pathfinders.benefits.rewards.title': 'Rich Incentives & Exclusive Rewards',
    'home.pathfinders.benefits.rewards.desc1': 'Complete basic tasks to get 10U basic reward',
    'home.pathfinders.benefits.rewards.desc2': 'Outstanding contributors can get 50U - 500U advanced rewards',
    'home.pathfinders.benefits.funding.title': 'Startup & Funding Support',
    'home.pathfinders.benefits.funding.desc1': 'Core members will receive comprehensive support including startup guidance and resource connections',
    'home.pathfinders.benefits.funding.desc2': 'Opportunities to connect with quality incubators, investors, and partners',
    'home.pathfinders.benefits.launchpad.title': 'Launchpad Privileges',
    'home.pathfinders.benefits.launchpad.desc1': 'Core Pathfinders can prioritize access to upcoming platform projects, participate in testing, AMA, and strategic discussions',
    'home.pathfinders.benefits.launchpad.desc2': 'Enjoy opportunities for direct communication with project teams and investors, truly at the forefront of ecosystem building',
    'home.pathfinders.benefits.nft.title': 'Ambassador NFT Identity Badge',
    'home.pathfinders.benefits.nft.desc1': 'Specific levels will receive honorary Pathfinders NFT as an irreplaceable symbol of honor',
    'home.pathfinders.benefits.nft.desc2': 'NFT will become your digital credential in the Flipflop community, permanently inscribing your contributions',
    'home.pathfinders.benefits.community.title': 'Community Influence & Co-building Rights',
    'home.pathfinders.benefits.community.desc1': 'Every participant has the opportunity to appear on the official website, Pathfinders leaderboard, and official Space for more exposure',
    'home.pathfinders.benefits.community.desc2': 'Core members will directly participate in Flipflop\'s strategic discussions and jointly determine the future direction of the ecosystem',
    
    // Forms translations
    'forms.application.title': 'Pathfinders Application Form',
    'forms.achievement.title': 'Achievement Submission Form',
    'forms.activity.title': 'Activity Organization Application Form',
    'forms.required': '*',
    'forms.optional.note': 'Note: Fields marked with * are required, others are optional',
    'forms.submit.button': 'Submit Application',
    'forms.cancel.button': 'Cancel',
    'forms.submit.achievement': 'Submit Achievement',
    
    // Common form fields
    'forms.field.name': 'Name',
    'forms.field.email': 'Email',
    'forms.field.twitter': 'Twitter/X Username',
    'forms.field.telegram': 'Telegram Username',
    'forms.field.wallet': 'Wallet Address',
    'forms.field.wallet.solana': 'Wallet Address (Solana)',
    'forms.field.wallet.both': 'Wallet Address (Solana, USDT)',
    
    // Application form specific
    'forms.application.web3role': 'Web3 Participation Role',
    'forms.application.expertise': 'Area of Expertise',
    'forms.application.portfolio': 'Portfolio/Past Contributions Link (if available, please attach)',
    'forms.application.motivation': 'Why do you want to join Pathfinders?',
    'forms.application.weeklyhours': 'Weekly time commitment (hours or frequency)',
    'forms.application.events': 'Are you willing to participate in online/offline event organization?',
    'forms.application.resources': 'Do you have resources or channels to support Flipflop (media, KOL, community)?',
    'forms.application.entrepreneurship': 'Do you have entrepreneurial ideas/incubation needs?',
    
    // Web3 roles
    'forms.role.entrepreneur': 'Entrepreneur',
    'forms.role.developer': 'Developer',
    'forms.role.creator': 'Content Creator',
    'forms.role.kol': 'KOL',
    'forms.role.community': 'Community Builder',
    'forms.role.marketing': 'Operations/Marketing',
    'forms.role.researcher': 'Researcher',
    'forms.role.enthusiast': 'Enthusiast',
    'forms.role.student': 'Student',
    
    // Expertise areas
    'forms.expertise.content': 'Content Creation',
    'forms.expertise.community': 'Community Activities',
    'forms.expertise.research': 'Research Writing',
    'forms.expertise.promotion': 'Promotion & Marketing',
    
    // Achievement form specific
    'forms.achievement.category': 'Submission Category',
    'forms.achievement.tasktype': 'Specific Task Type',
    'forms.achievement.contentlink': 'Content Link',
    'forms.achievement.screenshot': 'Screenshot Proof (file upload available)',
    'forms.achievement.completion': 'Completion Date',
    'forms.achievement.description': 'Brief Description (content highlights/promotion effect)',
    
    // Categories
    'forms.category.promotion': 'Promotion',
    'forms.category.creation': 'Creation',
    'forms.category.community': 'Community',
    
    // Task types
    'forms.task.like': '+0.5 Official content one-click triple (retweet + like + comment)',
    'forms.task.content': '+2 Original content / Meme / Platform tutorials',
    'forms.task.article': '+8-10 Long-form or in-depth articles / Mechanism understanding & application (≥500 words)',
    'forms.task.video': '+12-15 Short videos (≥30 seconds)',
    'forms.task.ama': '+2-3 Participate in AMA / Online events, ask questions or join discussions',
    'forms.task.recap': '+8-10 AMA Recap (≥500 words)',
    'forms.task.telegram': '+2–3 Telegram topic discussions',
    'forms.task.offline': '+25-30 Successfully organize an officially certified offline event',
    
    // Activity form specific
    'forms.activity.organizer': 'Organizer',
    'forms.activity.type': 'Activity Type',
    'forms.activity.theme': 'Activity Theme',
    'forms.activity.introduction': 'Brief Introduction',
    'forms.activity.time': 'Activity Time',
    'forms.activity.location': 'Activity Location',
    'forms.activity.scale': 'Activity Scale',
    'forms.activity.goals': 'Activity Goals',
    'forms.activity.audience': 'Target Audience',
    'forms.activity.process': 'Activity Process',
    'forms.activity.financial': 'Financial support needed from FlipFlop with detailed explanation (itemized expenses preferred)',
    'forms.activity.support': 'Other support needed from FlipFlop',
    'forms.activity.speakers': 'Intended speakers or presenters (if any)',
    'forms.activity.partners': 'Partners (such as joint communities/KOL)',
    'forms.activity.results': 'Expected outcomes (attendance, reach, media coverage, etc.)',
    
    // Activity types
    'forms.acttype.online': 'Online',
    'forms.acttype.offline': 'Offline',
    'forms.acttype.hybrid': 'Online + Offline',
    
    // Target audience
    'forms.audience.newusers': 'New Users',
    'forms.audience.community': 'Community/KOL',
    'forms.audience.projects': 'Project Teams',
    'forms.audience.makers': 'Market Makers',
    
    // Placeholders
    'forms.placeholder.username': '@username',
    'forms.placeholder.portfolio': 'Please provide links to your portfolio or past contributions',
    'forms.placeholder.motivation': 'Please describe your motivation and expectations for joining Pathfinders',
    'forms.placeholder.weeklyhours': 'e.g., 10 hours/week or 2 hours daily',
    'forms.placeholder.events': 'Yes/No, and specific ideas',
    'forms.placeholder.resources': 'Please describe the resources or channels you can provide',
    'forms.placeholder.entrepreneurship': 'Please describe your entrepreneurial ideas or incubation needs',
    'forms.placeholder.contentlink': 'Please provide the link to relevant content',
    'forms.placeholder.description': 'Please briefly describe content highlights or promotion effects',
    'forms.placeholder.location': 'Specific address or online platform',
    'forms.placeholder.scale': 'Expected number of participants',
    'forms.placeholder.introduction': 'Please briefly introduce the activity content and purpose',
    'forms.placeholder.goals': 'Please describe the expected goals of the activity',
    'forms.placeholder.process': 'Please describe the detailed schedule and process of the activity',
    'forms.placeholder.financial': 'Please list detailed financial support needs and purposes',
    'forms.placeholder.support': 'Such as technical support, promotion, speaker recommendations, etc.',
    'forms.placeholder.speakers': 'Please provide speaker names and backgrounds',
    'forms.placeholder.partners': 'Please list partner information',
    'forms.placeholder.results': 'Please describe expected activity effects and outcomes',
    
    // File upload
    'forms.upload.text': 'Upload File',
    'forms.upload.drag': 'or drag here',
    'forms.upload.format': 'PNG, JPG, GIF max 10MB'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    // Only access localStorage after component mounts
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'en')) {
        setLanguage(savedLanguage);
      }
    }
  }, []);

  useEffect(() => {
    // Only save to localStorage after component is mounted and on client side
    if (mounted && typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language, mounted]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'zh' ? 'en' : 'zh');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.zh] || key;
  };

  const formatDate = (date: string): string => {
    if (!date) return '';
    const [year, month, day] = date.split('-');
    if (language === 'zh') {
      return `${year}年${month}月${day}日`;
    } else {
      return `${month}/${day}/${year}`;
    }
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, formatDate }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}